//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class criteriosDeAceptacion
    {
        public string idHU { get; set; }
        public int numCriterio { get; set; }
        public string nombre { get; set; }
        public string contexto { get; set; }
        public string evento { get; set; }
        public string resultado { get; set; }
    
        public virtual historiasDeUsuario historiasDeUsuario { get; set; }
    }
}
