

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProyectoPP.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class patopurificEntitiesGeneral : DbContext
{
    public patopurificEntitiesGeneral()
        : base("name=patopurificEntitiesGeneral")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }

    public virtual DbSet<criteriosDeAceptacion> criteriosDeAceptacion { get; set; }

    public virtual DbSet<fechas> fechas { get; set; }

    public virtual DbSet<historiasDeUsuario> historiasDeUsuario { get; set; }

    public virtual DbSet<permisos> permisos { get; set; }

    public virtual DbSet<persona> persona { get; set; }

    public virtual DbSet<progreso> progreso { get; set; }

    public virtual DbSet<proyecto> proyecto { get; set; }

    public virtual DbSet<sprint> sprint { get; set; }

    public virtual DbSet<tarea> tarea { get; set; }

}

}

