//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public persona()
        {
            this.proyecto1 = new HashSet<proyecto>();
            this.tarea = new HashSet<tarea>();
        }

        [Display(Name = "Nombre")]
        [RegularExpression(@"^[a-zA-Z''-'\s]+$", ErrorMessage = "El nombre solo puede estar compuesto por letras.")]
        [Required(ErrorMessage = "Es requerido")]
        public string nombre { get; set; }

        [Required(ErrorMessage = "Es requerido")]
        [Display(Name = "Primer apellido")]
        [RegularExpression(@"^[a-zA-Z''-'\s]+$", ErrorMessage = "El primer apellido solo puede estar compuesto por letras")]
        public string apellido1 { get; set; }

        [Required(ErrorMessage = "Es requerido")]
        [Display(Name = "Segundo apellido")]
        [RegularExpression(@"^[a-zA-Z''-'\s]+$", ErrorMessage = "El segundo apellido solo puede estar compuesto por letras")]
        public string apellido2 { get; set; }

        [Required(ErrorMessage = "Es requerido")]

        public string cedula { get; set; }

        public string carne { get; set; }
        [Required(ErrorMessage = "Es requerido")]
        public string email { get; set; }

        public string id { get; set; }
        public string IdProyecto { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual proyecto proyecto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<proyecto> proyecto1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tarea> tarea { get; set; }
    }
}
