
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProyectoPP.Models
{

    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class persona
{

        [Display(Name = "Nombre")]
        public string nombre { get; set; }

        [Display(Name = "Primer apellido")]
        public string apellido1 { get; set; }

        [Display(Name = "Segundo apellido")]
        public string apellido2 { get; set; }

        [Display(Name = "Cédula")]
        public string cedula { get; set; }

        [Display(Name = "Carné")]
        public string carne { get; set; }

        [Display(Name = "Correo electrónico")]
        public string email { get; set; }

    public string id { get; set; }

}

}
