
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProyectoPP.Models
{

using System;
    using System.Collections.Generic;
    
public partial class persona
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public persona()
    {

        this.proyecto1 = new HashSet<proyecto>();

        this.tarea = new HashSet<tarea>();

    }


    public string nombre { get; set; }

    public string apellido1 { get; set; }

    public string apellido2 { get; set; }

    public string cedula { get; set; }

    public string carne { get; set; }

    public string email { get; set; }

    public string id { get; set; }

    public string IdProyecto { get; set; }



    public virtual AspNetUsers AspNetUsers { get; set; }

    public virtual proyecto proyecto { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<proyecto> proyecto1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tarea> tarea { get; set; }

}

}
